#################################################################################
# TODO:
#################################################################################
# Use the cache to load gem faster: https://docs.knapsackpro.com/2021/how-to-load-ruby-gems-from-cache-on-github-actions

name: Run Linguist (with caching and python)

on: workflow_dispatch

env:
  REPO: thislambert/AccessGitIntegration  # Define the repository here
  OPTIONS: '--breakdown'       # Define the options for Linguist here


jobs:
  test:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v4

    - name: Bash
      run: |
        ls
      shell: bash

    - uses: ruby/setup-ruby@v1
      with:
        # Not needed with a .ruby-version file
        ruby-version: 3.2
        # runs 'bundle install' and caches installed gems automatically
        bundler-cache: true

    # - name: Add bin to PATH
    #   run: |
    #     BIN_PATH="$(bundle info github-linguist --path)/bin"
    #     echo "BIN_PATH: $BIN_PATH"
    #     echo "$BIN_PATH" >> $GITHUB_PATH
    #     echo "Updated GITHUB_PATH: $GITHUB_PATH"
    #     echo "Updated PATH: $PATH"
    #     ls "$BIN_PATH"
    #   shell: bash

    - name: Clone repo
      run: |
        mkdir repo
        cd repo
        git clone "https://github.com/${{ env.REPO }}"
      shell: bash

    # - name: Run Linguist
    #   run: |
    #     #github-linguist repo/PuzzleTak_AudioPlayer ${{ env.OPTIONS }}
    #     REPO_NAME=$(echo "${{ env.REPO }}" | cut -d'/' -f2)
    #     bundle exec github-linguist "repo/$REPO_NAME" {{ env.OPTIONS }}
    #   shell: bash

    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
    - name: Install Python dependencies
      run: |
        pip install -r requirements.txt
        git clone https://github.com/DecimalTurn/linguist-python.git --depth 1
        cd linguist-python
        # Make your code changes here
        pip install .
        cd ..
      shell: bash
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Run Python script
      run: |
        REPO_NAME=$(echo "${{ env.REPO }}" | cut -d'/' -f2)
        python run.py "repo/$REPO_NAME"
      shell: bash
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}    
